services:

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: npg_iz2ua3LFjCtq@ep-empty-queen-a2zsd65n-pooler
      POSTGRES_DB: easydesk
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://neondb_owner:npg_iz2ua3LFjCtq@ep-empty-queen-a2zsd65n-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require
      NODE_ENV: production
      JWT_SECRET: Ue8$@14kFz!9nVxZ
    depends_on:
      - db



volumes:
  postgres_data:


